# Generated by Django 3.1.7 on 2021-02-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('nim', models.CharField(max_length=10)),
                ('alamat', models.TextField()),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
