# Generated by Django 3.1.7 on 2021-02-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
